apiVersion: v1
kind: Pod
metadata:
  name: ssh-pod
  labels:
    name: ssh-pod
spec:
  containers:
  - name: ssh-pod-container
    image: 610183257700.dkr.ecr.eu-west-1.amazonaws.com/stock/ssh-docker-container:latest
    env:
    - name: USER_SSH_ALLOWED
      value: "!SSH_PUBLIC_KEYS!"